import LogoImg from "../assets/Logo.png";

import "../styles/global.scss";
import Image from "next/image";

export const metadata = {
  title: "Ignite Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="ml-auto flex min-h-screen max-w-shopScreen flex-col items-start justify-center">
          <header className="w-full py-8">
            <Image src={LogoImg} alt="logo" />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
